### ISSUE TITLE
Log in the toolbox

### ISSUE THREAD

**Issue by Reny900** [tera-classic-mods/fps-utils#1]
Noticed this using fps-utils. 
[10:54:37.025] [dispatch] write: C_REQUEST_CONTRACT<1> is not latest version (50)
    at Proxy.toServer (D:\Games\Akeron_Tera_Online\Toolbox\bin\mod.js:333:30)
    at String.<anonymous> (D:\Games\Akeron_Tera_Online\Toolbox\mods\fps-utils\lib\index.js:1546:11)
    at CommandBase.exec (D:\Games\Akeron_Tera_Online\Toolbox\mods\command\index.js:225:16)
    at Command.exec (D:\Games\Akeron_Tera_Online\Toolbox\mods\command\index.js:403:26)
    at Object.callback (D:\Games\Akeron_Tera_Online\Toolbox\mods\fps-utils\lib\index.js:56:23)
    at Dispatch.handle (D:\Games\Akeron_Tera_Online\Toolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:415:45)
    at Dispatch.write (D:\Games\Akeron_Tera_Online\Toolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:321:21)
    at Proxy.send (D:\Games\Akeron_Tera_Online\Toolbox\bin\mod.js:345:38)
    
    Fps utils still working after toolbox prints out this message. just a heads up

**Comment by justkeepquiet** [comment]
Hi. The problem has been fixed, the "Mail" button is now working.
